### ISSUE TITLE
Update to latest system_properties

### ISSUE THREAD

**Issue by aviraxp** [topjohnwu/system_properties#4]
Android 14 QPR2 introduced property override which allows certain props to be different in each process.

https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/system_properties

**Comment by snake-4** [comment]
They are not different per process per se. It's just a mirror of the actual prop area for the time being.

I don't think they are actually used anywhere else yet unless I'm mistaken.

**Comment by ghost** [comment]
Updated for custom ROMs :D
https://github.com/chiteroman/android_bionic

**Comment by topjohnwu** [comment]
Done :)
